import Header from "../components/Header";
import Footer from "../components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		default: 'Our Next.JS Tutorial | The Faddah Company',
		template: '%s | The Faddah Company'
	},
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body style={{ height: "10vh", width: "100vw" }}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
