import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body style={{ height: "10vh", width: "100vw" }}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
